# Generated by Django 6.1 on 2026-08-28 13:41

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=40)),
                ('supplier_invoice_reference', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('pharmacy_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('currency_code', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices_posted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='parties.supplier')),
            ],
            options={
                'db_table': 'purchasing_purchase_invoice',
                'permissions': [('post_purchaseinvoice', 'Can post purchase invoice')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_description_snapshot', models.CharField(max_length=240)),
                ('unit_name_snapshot', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('conversion_to_base_snapshot', models.DecimalField(decimal_places=6, max_digits=14)),
                ('received_quantity_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='catalog.medicine')),
                ('medicine_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='inventory.medicinebatch')),
                ('medicine_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='catalog.medicineunit')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.purchaseinvoice')),
            ],
            options={
                'db_table': 'purchasing_purchase_invoice_line',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', 'invoice_date'], name='purchasing_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status', 'payment_status'], name='purchasing_status_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'POSTED')), fields=('invoice_number',), name='purchasing_posted_invoice_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'POSTED'), _negated=True), models.Q(('invoice_number', ''), _negated=True), _connector='OR'), name='purchasing_posted_invoice_has_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('discount_total__gte', 0), ('tax_total__gte', 0), ('grand_total__gte', 0), ('paid_total__gte', 0), ('remaining_balance__gte', 0)), name='purchasing_invoice_totals_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_balance', django.db.models.expressions.CombinedExpression(models.F('grand_total'), '-', models.F('paid_total')))), name='purchasing_invoice_balance_matches'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchasing_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_to_base_snapshot__gt', 0)), name='purchasing_line_conversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity_base__gt', 0)), name='purchasing_line_received_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0), ('discount_amount__gte', 0), ('tax_rate_percent__gte', 0), ('tax_rate_percent__lte', 100), ('tax_amount__gte', 0), ('line_total__gte', 0)), name='purchasing_line_amounts_valid'),
        ),
    ]
