# Generated by Django 6.1 on 2026-08-28 13:41

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('pharmacy_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=32)),
                ('currency_code', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='parties.customer')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'sales_sales_invoice',
                'permissions': [('complete_sale', 'Can complete sale')],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_description_snapshot', models.CharField(max_length=240)),
                ('unit_name_snapshot', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('conversion_to_base_snapshot', models.DecimalField(decimal_places=6, max_digits=14)),
                ('requested_quantity_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prescription_required_snapshot', models.BooleanField(default=False)),
                ('prescription_warning_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='catalog.medicine')),
                ('medicine_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='catalog.medicineunit')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salesinvoice')),
            ],
            options={
                'db_table': 'sales_sales_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='SaleBatchAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_quantity_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('acquisition_cost_snapshot', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='inventory.medicinebatch')),
                ('sales_invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_allocations', to='sales.salesinvoiceline')),
            ],
            options={
                'db_table': 'sales_sale_batch_allocation',
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status', 'completed_at'], name='sales_status_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', 'payment_status'], name='sales_customer_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'COMPLETED')), fields=('invoice_number',), name='sales_completed_invoice_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('invoice_number', ''), _negated=True), _connector='OR'), name='sales_completed_invoice_has_number'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('discount_total__gte', 0), ('tax_total__gte', 0), ('grand_total__gte', 0), ('paid_total__gte', 0), ('balance_due__gte', 0)), name='sales_invoice_totals_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('balance_due', django.db.models.expressions.CombinedExpression(models.F('grand_total'), '-', models.F('paid_total')))), name='sales_invoice_balance_matches'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('status', 'COMPLETED'), _negated=True), ('balance_due', 0), _connector='OR'), name='sales_walkin_completed_settled'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_to_base_snapshot__gt', 0)), name='sales_line_conversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity_base__gt', 0)), name='sales_line_requested_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('discount_amount__gte', 0), ('tax_rate_percent__gte', 0), ('tax_rate_percent__lte', 100), ('tax_amount__gte', 0), ('line_total__gte', 0)), name='sales_line_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='salebatchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity_base__gt', 0)), name='sales_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salebatchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('acquisition_cost_snapshot__gte', 0)), name='sales_allocation_cost_nonnegative'),
        ),
    ]
