# Generated by Django 6.1 on 2026-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_inventory_movement_source_line_unique'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salebatchallocation',
            constraint=models.UniqueConstraint(fields=('sales_invoice_line', 'batch'), name='sales_allocation_line_batch_unique'),
        ),
    ]
