# Generated by Django 6.1 on 2026-08-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'permissions': [('post_customerpayment', 'Can post customer payment'), ('view_financial_reports', 'Can view financial reports')]},
        ),
    ]
