# Generated by Django 6.1 on 2026-08-28 13:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=40, unique=True)),
                ('reason', models.TextField()),
                ('return_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='parties.customer')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns_processed', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='sales.salesinvoice')),
            ],
            options={
                'db_table': 'returns_customer_return',
                'permissions': [('post_customerreturn', 'Can post customer return')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('refunded_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_refunds', to='core.paymentmethod')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_refunds_processed', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.salesinvoice')),
                ('customer_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='returns.customerreturn')),
            ],
            options={
                'db_table': 'returns_customer_refund',
                'permissions': [('process_refund', 'Can process customer refund')],
            },
        ),
        migrations.CreateModel(
            name='CustomerReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('returned_quantity_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('condition', models.CharField(choices=[('RESALABLE', 'Resalable'), ('NON_RESELLABLE', 'Non-resellable')], max_length=20)),
                ('restock', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_return_lines', to='inventory.medicinebatch')),
                ('customer_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='returns.customerreturn')),
                ('sales_invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_return_lines', to='sales.salesinvoiceline')),
            ],
            options={
                'db_table': 'returns_customer_return_line',
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=40, unique=True)),
                ('reason', models.TextField()),
                ('return_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns_processed', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='purchasing.purchaseinvoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='parties.supplier')),
            ],
            options={
                'db_table': 'returns_supplier_return',
                'permissions': [('post_supplierreturn', 'Can post supplier return')],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('returned_quantity_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_lines', to='inventory.medicinebatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_lines', to='catalog.medicine')),
                ('supplier_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='returns.supplierreturn')),
            ],
            options={
                'db_table': 'returns_supplier_return_line',
            },
        ),
        migrations.AddIndex(
            model_name='customerreturn',
            index=models.Index(fields=['sales_invoice', 'status'], name='returns_customer_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerreturn',
            constraint=models.CheckConstraint(condition=models.Q(('return_total__gte', 0)), name='returns_customer_total_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='customerrefund',
            index=models.Index(fields=['customer_return', 'status', 'refunded_at'], name='returns_refund_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='returns_customer_refund_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity_base__gt', 0)), name='returns_customer_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='returns_customer_line_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('restock', False), ('condition', 'RESALABLE'), _connector='OR'), name='returns_restock_requires_resalable'),
        ),
        migrations.AddIndex(
            model_name='supplierreturn',
            index=models.Index(fields=['supplier', 'status'], name='returns_supplier_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturn',
            constraint=models.CheckConstraint(condition=models.Q(('return_total__gte', 0)), name='returns_supplier_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity_base__gt', 0)), name='returns_supplier_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0), ('line_total__gte', 0)), name='returns_supplier_line_amounts_nonnegative'),
        ),
    ]
