# Generated by Django 6.1 on 2026-08-28 17:31

from django.db import migrations, models


def correct_resellable_condition(apps, schema_editor):
    CustomerReturnLine = apps.get_model("returns", "CustomerReturnLine")
    CustomerReturnLine.objects.using(schema_editor.connection.alias).filter(
        condition="RESALABLE"
    ).update(condition="RESELLABLE")


def restore_resalable_condition(apps, schema_editor):
    CustomerReturnLine = apps.get_model("returns", "CustomerReturnLine")
    CustomerReturnLine.objects.using(schema_editor.connection.alias).filter(
        condition="RESELLABLE"
    ).update(condition="RESALABLE")


def require_no_reversed_refunds(apps, schema_editor):
    CustomerRefund = apps.get_model("returns", "CustomerRefund")
    if CustomerRefund.objects.using(schema_editor.connection.alias).filter(
        status="REVERSED"
    ).exists():
        raise RuntimeError(
            "Cannot remove CustomerRefund.REVERSED while reversed refund rows exist. "
            "Resolve those records explicitly before applying this migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('returns', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerreturnline',
            name='returns_restock_requires_resalable',
        ),
        migrations.RunPython(
            correct_resellable_condition,
            restore_resalable_condition,
        ),
        migrations.RunPython(
            require_no_reversed_refunds,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='customerrefund',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted')], default='POSTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='condition',
            field=models.CharField(choices=[('RESELLABLE', 'Resellable'), ('NON_RESELLABLE', 'Non-resellable')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customerrefund',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'POSTED')), name='returns_customer_refund_posted_only'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('restock', False), ('condition', 'RESELLABLE'), _connector='OR'), name='returns_restock_requires_resellable'),
        ),
    ]
