# Generated by Django 6.1 on 2026-08-28 13:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('requires_reference', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_payment_method',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rate_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_tax_rate',
                'constraints': [models.CheckConstraint(condition=models.Q(('rate_percent__gte', 0), ('rate_percent__lte', 100)), name='core_tax_rate_percent_range')],
            },
        ),
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('expiry_warning_days', models.PositiveIntegerField(default=90)),
                ('default_low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('invoice_header', models.TextField(blank=True)),
                ('invoice_footer', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_settings', to='core.taxrate')),
            ],
            options={
                'verbose_name_plural': 'pharmacy settings',
                'db_table': 'core_pharmacy_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='core_pharmacy_settings_singleton'), models.CheckConstraint(condition=models.Q(('default_low_stock_threshold__gte', 0)), name='core_pharmacy_settings_low_stock_nonnegative')],
            },
        ),
    ]
