# Generated by Django 6.1 on 2026-08-28 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('prescription_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='parties.customer')),
                ('prescriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='parties.prescriber')),
            ],
            options={
                'db_table': 'prescriptions_prescription',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_prescribed', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='catalog.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescriptions_prescription_item',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_date'], name='prescriptions_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_prescribed__isnull', True), ('quantity_prescribed__gt', 0), _connector='OR'), name='prescriptions_item_quantity_positive'),
        ),
    ]
