# Generated by Django 6.1 on 2026-08-28 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('acquisition_cost_per_base_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_available_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('first_received_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.medicine')),
            ],
            options={
                'db_table': 'inventory_medicine_batch',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase receipt'), ('SALE', 'Sale'), ('CUSTOMER_RETURN_RESTOCK', 'Customer return restock'), ('SUPPLIER_RETURN', 'Supplier return'), ('MANUAL_ADJUSTMENT_IN', 'Manual adjustment in'), ('MANUAL_ADJUSTMENT_OUT', 'Manual adjustment out')], max_length=32)),
                ('quantity_delta_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.UUIDField()),
                ('source_line_id', models.UUIDField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.medicinebatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.medicine')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_stock_movement',
            },
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'is_active', 'expiry_date', 'first_received_at'], name='inventory_batch_fefo_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['expiry_date', 'is_active'], name='inventory_batch_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number', 'expiry_date', 'acquisition_cost_per_base_unit'), name='inventory_batch_cost_layer_unique'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(condition=models.Q(('acquisition_cost_per_base_unit__gte', 0)), name='inventory_batch_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available_base__gte', 0)), name='inventory_batch_quantity_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch', 'occurred_at'], name='inventory_move_batch_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source_type', 'source_id'], name='inventory_move_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta_base', 0), _negated=True), name='inventory_movement_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['PURCHASE_RECEIPT', 'CUSTOMER_RETURN_RESTOCK', 'MANUAL_ADJUSTMENT_IN']), ('quantity_delta_base__gt', 0)), models.Q(('movement_type__in', ['SALE', 'SUPPLIER_RETURN', 'MANUAL_ADJUSTMENT_OUT']), ('quantity_delta_base__lt', 0)), _connector='OR'), name='inventory_movement_delta_direction'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__isnull', True), ('unit_cost_snapshot__gte', 0), _connector='OR'), name='inventory_movement_cost_nonnegative'),
        ),
    ]
