# Generated by Django 6.1 on 2026-08-29 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_line_id__isnull', False)), fields=('movement_type', 'source_type', 'source_id', 'source_line_id'), name='inventory_movement_source_line_unique'),
        ),
    ]
