"""Project-level dashboard navigation.

Feature apps can add their URL name and optional Django permission here when
they are introduced. Missing URL names are handled as disabled links.
"""

DASHBOARD_NAVIGATION = (
    {
        "section": "Main",
        "label": "Dashboard",
        "icon": "dashboard",
        "url_name": "dashboard:home",
        "namespace": "dashboard",
        "permission": None,
        "groups": None,  # everyone
    },
    {
        "section": "Main",
        "label": "Sales",
        "icon": "sales",
        "url_name": None,
        "namespace": "sales",
        "permission": None,
        "groups": ("Owner / Admin", "Pharmacist"),
    },
    {
        "section": "Management",
        "label": "Medicines",
        "icon": "medicines",
        "url_name": None,
        "namespace": "medicines",
        "permission": None,
        "groups": ("Owner / Admin", "Pharmacist", "Inventory Manager"),
    },
    {
        "section": "Management",
        "label": "Inventory",
        "icon": "inventory",
        "url_name": None,
        "namespace": "inventory",
        "permission": None,
        "groups": ("Owner / Admin", "Pharmacist", "Inventory Manager"),
    },
    {
        "section": "Management",
        "label": "Suppliers",
        "icon": "suppliers",
        "url_name": None,
        "namespace": "suppliers",
        "permission": None,
        "groups": ("Owner / Admin", "Inventory Manager"),
    },
    {
        "section": "Management",
        "label": "Customers",
        "icon": "customers",
        "url_name": None,
        "namespace": "customers",
        "permission": None,
        "groups": ("Owner / Admin", "Pharmacist"),
    },
    {
        "section": "Management",
        "label": "Prescriptions",
        "icon": "prescriptions",
        "url_name": None,
        "namespace": "prescriptions",
        "permission": None,
        "groups": ("Owner / Admin", "Pharmacist"),
    },
    {
        "section": "Transactions",
        "label": "Purchases",
        "icon": "purchases",
        "url_name": None,
        "namespace": "purchases",
        "permission": None,
        "groups": ("Owner / Admin", "Inventory Manager"),
    },
    {
        "section": "Transactions",
        "label": "Invoices",
        "icon": "invoices",
        "url_name": None,
        "namespace": "invoices",
        "permission": None,
        "groups": ("Owner / Admin", "Pharmacist", "Accountant"),
    },
    {
        "section": "Transactions",
        "label": "Payments",
        "icon": "payments",
        "url_name": None,
        "namespace": "payments",
        "permission": None,
        "groups": ("Owner / Admin", "Accountant"),
    },
    {
        "section": "Transactions",
        "label": "Returns & Refunds",
        "icon": "returns",
        "url_name": None,
        "namespace": "returns",
        "permission": None,
        "groups": ("Owner / Admin", "Pharmacist"),
    },
    {
        "section": "Reports",
        "label": "Reports",
        "icon": "reports",
        "url_name": None,
        "namespace": "reports",
        "permission": None,
        "groups": ("Owner / Admin", "Accountant"),
    },
    {
        "section": "System",
        "label": "Settings",
        "icon": "settings",
        "url_name": None,
        "namespace": "settings",
        "permission": None,
        "groups": ("Owner / Admin",),
    },
    {
        "section": "System",
        "label": "Logout",
        "icon": "logout",
        "url_name": "accounts:logout",
        "namespace": None,
        "permission": None,
        "groups": None,
        "method": "post",
    },
)
