"""Project-level dashboard navigation.

Feature apps add their URL name and Django permission here when introduced.
Missing URL names are handled as disabled links.

Groups organize permissions; navigation checks permissions only.
"""


DASHBOARD_NAVIGATION = (
    {
        "section": "Main",
        "label": "Dashboard",
        "icon": "dashboard",
        "url_name": "dashboard:home",
        "namespace": "dashboard",
        "permission": None,
    },
    {
        "section": "Main",
        "label": "Sales",
        "icon": "sales",
        "url_name": "sales:pos",
        "namespace": "sales",
        "active_url_names": ("pos", "pos-workspace"),
        "permission": "sales.view_salesinvoice",
    },
    {
        "section": "Management",
        "label": "Medicines",
        "icon": "medicines",
        "url_name": "catalog:medicine-list",
        "namespace": "catalog",
        "active_url_names": (
            "medicine-list", "medicine-create", "medicine-detail", "medicine-update",
            "medicine-toggle-active", "medicine-unit-create", "medicine-unit-update",
            "medicine-unit-toggle-active", "medicine-barcode-create",
            "medicine-barcode-toggle-active", "category-list", "category-create",
            "category-update", "category-toggle-active", "manufacturer-list",
            "manufacturer-create", "manufacturer-update", "manufacturer-toggle-active",
        ),
        "permission": "catalog.view_medicine",
    },
    {
        "section": "Management",
        "label": "Inventory",
        "icon": "inventory",
        "url_name": "inventory:batch-list",
        "namespace": "inventory",
        "active_url_names": ("batch-list", "batch-detail", "movement-list"),
        "permission": "inventory.view_medicinebatch",
    },
    {
        "section": "Management",
        "label": "Suppliers",
        "icon": "suppliers",
        "url_name": "parties:supplier-list",
        "namespace": "parties",
        "active_url_names": (
            "supplier-list", "supplier-create", "supplier-update", "supplier-toggle-active",
        ),
        "permission": "parties.view_supplier",
    },
    {
        "section": "Management",
        "label": "Customers",
        "icon": "customers",
        "url_name": "parties:customer-list",
        "namespace": "parties",
        "active_url_names": (
            "customer-list", "customer-create", "customer-update", "customer-toggle-active",
        ),
        "permission": "parties.view_customer",
    },
    {
        "section": "Management",
        "label": "Prescriptions",
        "icon": "prescriptions",
        "url_name": "prescriptions:list",
        "namespace": "prescriptions",
        "active_url_names": ("list", "create", "detail", "update"),
        "permission": "prescriptions.view_prescription",
    },
    {
        "section": "Transactions",
        "label": "Purchases",
        "icon": "purchases",
        "url_name": "purchasing:purchase-invoice-list",
        "namespace": "purchasing",
        "active_url_names": (
            "purchase-invoice-list", "purchase-invoice-create",
            "purchase-invoice-detail", "purchase-invoice-post",
        ),
        "permission": "purchasing.view_purchaseinvoice",
    },
    {
        "section": "Transactions",
        "label": "Invoices",
        "icon": "invoices",
        "url_name": "sales:invoice-list",
        "namespace": "sales",
        "active_url_names": ("invoice-list", "invoice-detail", "invoice-print"),
        "permission": "sales.view_salesinvoice",
    },
    {
        "section": "Transactions",
        "label": "Payments",
        "icon": "payments",
        "url_name": "finance:payment-list",
        "namespace": "finance",
        "permission": None,
        "any_permissions": ("finance.view_customerpayment", "finance.view_supplierpayment"),
    },
    {
        "section": "Transactions",
        "label": "Returns & Refunds",
        "icon": "returns",
        "url_name": "returns:home",
        "namespace": "returns",
        "active_url_names": (
            "home", "customer-return-list", "customer-return-create",
            "customer-return-detail", "customer-return-post", "customer-refund-create",
            "supplier-return-list", "supplier-return-create",
            "supplier-return-detail", "supplier-return-post",
        ),
        "permission": None,
        "any_permissions": ("returns.view_customerreturn", "returns.view_supplierreturn"),
    },
    {
        "section": "Reports",
        "label": "Reports",
        "icon": "reports",
        "url_name": None,
        "namespace": "reports",
        "permission": "finance.view_financial_reports",
    },
    {
        "section": "System",
        "label": "Settings",
        "icon": "settings",
        "url_name": "core:settings",
        "namespace": "core",
        "permission": "core.change_pharmacysettings",
    },
    {
        "section": "System",
        "label": "Staff Accounts",
        "icon": "customers",
        "url_name": "accounts:staff-list",
        "namespace": "accounts",
        "active_url_names": (
            "staff-list", "staff-create", "staff-detail", "staff-update",
            "staff-role-update", "staff-status-update", "staff-password-reset",
        ),
        "permission": "auth.view_user",
        "required_group": "Owner / Admin",
    },
    {
        "section": "System",
        "label": "Roles & Permissions",
        "icon": "settings",
        "url_name": "accounts:role-permissions",
        "namespace": "accounts",
        "active_url_names": ("role-permissions", "role-permissions-update"),
        "permission": "auth.view_group",
        "required_group": "Owner / Admin",
    },
    {
        "section": "System",
        "label": "Logout",
        "icon": "logout",
        "url_name": "accounts:logout",
        "namespace": None,
        "permission": None,
        "method": "post",
    },
)
