from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.template.loader import render_to_string
from django.test import RequestFactory, SimpleTestCase, TestCase
from django.urls import resolve, reverse

from config.context_processors import dashboard_navigation


class SharedComponentTests(SimpleTestCase):
    def test_icon_selects_named_path_and_applies_shared_svg_attributes(self):
        rendered = render_to_string(
            "components/icon.html",
            {"name": "dashboard", "class": "size-5 text-slate-500"},
        )

        self.assertIn('class="size-5 text-slate-500"', rendered)
        self.assertIn('viewBox="0 0 24 24"', rendered)
        self.assertIn('fill="none"', rendered)
        self.assertIn('stroke="currentColor"', rendered)
        self.assertIn('stroke-width="1.8"', rendered)
        self.assertIn('aria-hidden="true"', rendered)
        self.assertIn("M4 4h6v6H4z", rendered)
        self.assertNotIn("M4 7h16M4 12h16M4 17h16", rendered)

    def test_icon_renders_nothing_for_an_unknown_name(self):
        rendered = render_to_string(
            "components/icon.html",
            {"name": "not-registered", "class": "size-5"},
        )

        self.assertEqual(rendered.strip(), "")

    def test_button_supports_new_variants_and_sizes_with_legacy_danger_alias(self):
        destructive = render_to_string(
            "components/button.html",
            {"text": "Delete", "variant": "destructive", "size": "sm"},
        )
        legacy_danger = render_to_string(
            "components/button.html",
            {"text": "Delete", "variant": "danger"},
        )

        self.assertIn("h-8", destructive)
        self.assertIn("bg-red-600", destructive)
        self.assertIn("bg-red-600", legacy_danger)

    def test_input_associates_help_and_errors_and_supports_readonly(self):
        rendered = render_to_string(
            "components/input.html",
            {
                "id": "id_reference",
                "name": "reference",
                "label": "Reference",
                "help_text": "Generated by the system.",
                "error": "This value is invalid.",
                "readonly": True,
            },
        )

        self.assertIn('for="id_reference"', rendered)
        self.assertIn("readonly", rendered)
        self.assertIn('aria-invalid="true"', rendered)
        self.assertIn(
            'aria-describedby="id_reference-help id_reference-error"',
            rendered,
        )
        self.assertIn('id="id_reference-help"', rendered)
        self.assertIn('id="id_reference-error"', rendered)

    def test_textarea_and_select_share_accessible_supporting_text(self):
        textarea = render_to_string(
            "components/textarea.html",
            {
                "name": "notes",
                "help_text": "For internal use.",
                "readonly": True,
            },
        )
        select = render_to_string(
            "components/select.html",
            {
                "name": "category",
                "help_text": "Choose one category.",
                "options": [{"value": "otc", "label": "OTC"}],
            },
        )

        self.assertIn('aria-describedby="notes-help"', textarea)
        self.assertIn("readonly", textarea)
        self.assertIn('aria-describedby="category-help"', select)
        self.assertIn("appearance-none", select)

    def test_modal_description_is_programmatically_associated(self):
        rendered = render_to_string(
            "components/modal.html",
            {
                "modal_id": "confirmation",
                "title": "Confirm action",
                "description": "Review this change.",
                "body": "This cannot be undone.",
            },
        )

        self.assertIn('aria-describedby="confirmation-description"', rendered)
        self.assertIn('id="confirmation-description"', rendered)
        self.assertIn("data-modal-backdrop", rendered)


class DashboardNavigationTests(TestCase):
    role_permissions = {
        "Owner / Admin": "all",
        "Pharmacist": {
            "catalog.view_medicine",
            "inventory.view_medicinebatch",
            "parties.view_customer",
            "prescriptions.view_prescription",
            "returns.view_customerreturn",
            "sales.view_salesinvoice",
        },
        "Inventory Manager": {
            "catalog.view_medicine",
            "inventory.view_medicinebatch",
            "parties.view_supplier",
            "purchasing.view_purchaseinvoice",
        },
        "Accountant": {
            "finance.view_financial_reports",
            "finance.view_customerpayment",
            "sales.view_salesinvoice",
        },
    }
    role_items = {
        "Owner / Admin": {
            "Dashboard",
            "Sales",
            "Medicines",
            "Inventory",
            "Suppliers",
            "Customers",
            "Prescriptions",
            "Purchases",
            "Invoices",
            "Payments",
            "Returns & Refunds",
            "Reports",
            "Settings",
            "Logout",
        },
        "Pharmacist": {
            "Dashboard",
            "Sales",
            "Medicines",
            "Inventory",
            "Customers",
            "Prescriptions",
            "Invoices",
            "Returns & Refunds",
            "Logout",
        },
        "Inventory Manager": {
            "Dashboard",
            "Medicines",
            "Inventory",
            "Suppliers",
            "Purchases",
            "Logout",
        },
        "Accountant": {
            "Dashboard",
            "Sales",
            "Invoices",
            "Payments",
            "Reports",
            "Logout",
        },
    }

    def navigation_for(self, role_name):
        group = Group.objects.create(name=role_name)
        user = get_user_model().objects.create_user(
            username=role_name.lower().replace(" ", "-").replace("/", ""),
            password="test-password",
        )
        user.groups.add(group)

        configured_permissions = self.role_permissions[role_name]
        if configured_permissions == "all":
            permissions = Permission.objects.all()
        else:
            permissions = [
                Permission.objects.get(
                    content_type__app_label=permission_name.split(".", 1)[0],
                    codename=permission_name.split(".", 1)[1],
                )
                for permission_name in configured_permissions
            ]
        group.permissions.add(*permissions)

        dashboard_url = reverse("dashboard:home")
        request = RequestFactory().get(dashboard_url)
        request.user = user
        request.resolver_match = resolve(dashboard_url)
        return dashboard_navigation(request)["dashboard_navigation"]

    def test_navigation_preserves_role_visibility(self):
        for role_name, expected_labels in self.role_items.items():
            with self.subTest(role=role_name):
                items = self.navigation_for(role_name)
                self.assertEqual({item["label"] for item in items}, expected_labels)

    def test_reports_navigation_requires_financial_report_permission(self):
        pharmacist_items = self.navigation_for("Pharmacist")
        accountant_items = self.navigation_for("Accountant")

        self.assertNotIn("Reports", {item["label"] for item in pharmacist_items})
        self.assertIn("Reports", {item["label"] for item in accountant_items})

    def test_dashboard_is_active_and_future_modules_are_disabled(self):
        items = self.navigation_for("Owner / Admin")
        dashboard = next(item for item in items if item["label"] == "Dashboard")
        medicines = next(item for item in items if item["label"] == "Medicines")
        future_items = [
            item
            for item in items
            if item["label"] not in {"Dashboard", "Medicines", "Logout"}
        ]

        self.assertTrue(dashboard["is_active"])
        self.assertEqual(dashboard["url"], "/dashboard/")
        self.assertEqual(medicines["url"], "/catalog/medicines/")
        self.assertTrue(all(item["url"] is None for item in future_items))

    def test_sections_and_post_logout_are_exposed_to_the_template(self):
        items = self.navigation_for("Owner / Admin")
        logout_item = next(item for item in items if item["label"] == "Logout")

        self.assertEqual(
            {item["section"] for item in items},
            {"Main", "Management", "Transactions", "Reports", "System"},
        )
        self.assertEqual(logout_item["url"], "/accounts/logout/")
        self.assertEqual(logout_item["method"], "post")


class DashboardViewTests(TestCase):
    def setUp(self):
        self.user = get_user_model().objects.create_user(
            username="dashboard-user",
            password="test-password",
        )
        self.dashboard_url = reverse("dashboard:home")

    def grant(self, *permission_names):
        permissions = []
        for permission_name in permission_names:
            app_label, codename = permission_name.split(".", 1)
            permissions.append(
                Permission.objects.get(
                    content_type__app_label=app_label,
                    codename=codename,
                )
            )
        self.user.user_permissions.add(*permissions)

    def test_dashboard_uses_the_single_canonical_route(self):
        self.assertEqual(self.dashboard_url, "/dashboard/")
        self.assertEqual(resolve(self.dashboard_url).view_name, "dashboard:home")
        self.assertRedirects(
            self.client.get("/"),
            reverse("accounts:login"),
            fetch_redirect_response=False,
        )

    def test_dashboard_requires_authentication(self):
        response = self.client.get(self.dashboard_url)

        self.assertRedirects(
            response,
            f"{reverse('accounts:login')}?next={self.dashboard_url}",
        )

    def test_dashboard_replaces_the_component_preview(self):
        self.user.is_superuser = True
        self.user.is_staff = True
        self.user.save(update_fields=["is_superuser", "is_staff"])
        self.client.force_login(self.user)

        response = self.client.get(self.dashboard_url)

        self.assertContains(response, "Overview of today's pharmacy activity.")
        self.assertContains(response, "Today&#x27;s Sales")
        self.assertContains(response, "Recent Activity")
        self.assertContains(response, "Attention Required")
        self.assertNotContains(response, "Dashboard UI foundation")
        self.assertNotContains(response, ">Demo<")
        self.assertNotContains(response, "Form controls")

    def test_dashboard_widgets_are_filtered_by_permissions(self):
        self.grant(
            "inventory.view_medicinebatch",
            "purchasing.view_purchaseinvoice",
        )
        self.client.force_login(self.user)

        response = self.client.get(self.dashboard_url)

        self.assertContains(response, "Low Stock")
        self.assertContains(response, "Expiring Soon")
        self.assertContains(response, "Purchase received")
        self.assertContains(response, "Invoice PI-0298")
        self.assertNotContains(response, "Today&#x27;s Sales")
        self.assertNotContains(response, "Receivables")
        self.assertNotContains(response, "Customer payment")

    def test_dashboard_has_readable_empty_states_without_business_permissions(self):
        self.client.force_login(self.user)

        response = self.client.get(self.dashboard_url)

        self.assertContains(response, "No summary metrics are available.")
        self.assertContains(response, "No recent activity is available.")
        self.assertContains(response, "No attention items are available.")
