from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.template.loader import render_to_string
from django.test import RequestFactory, SimpleTestCase, TestCase
from django.urls import resolve

from config.context_processors import dashboard_navigation


class SharedComponentTests(SimpleTestCase):
    def test_button_supports_new_variants_and_sizes_with_legacy_danger_alias(self):
        destructive = render_to_string(
            "components/button.html",
            {"text": "Delete", "variant": "destructive", "size": "sm"},
        )
        legacy_danger = render_to_string(
            "components/button.html",
            {"text": "Delete", "variant": "danger"},
        )

        self.assertIn("h-8", destructive)
        self.assertIn("bg-red-600", destructive)
        self.assertIn("bg-red-600", legacy_danger)

    def test_input_associates_help_and_errors_and_supports_readonly(self):
        rendered = render_to_string(
            "components/input.html",
            {
                "id": "id_reference",
                "name": "reference",
                "label": "Reference",
                "help_text": "Generated by the system.",
                "error": "This value is invalid.",
                "readonly": True,
            },
        )

        self.assertIn('for="id_reference"', rendered)
        self.assertIn("readonly", rendered)
        self.assertIn('aria-invalid="true"', rendered)
        self.assertIn(
            'aria-describedby="id_reference-help id_reference-error"',
            rendered,
        )
        self.assertIn('id="id_reference-help"', rendered)
        self.assertIn('id="id_reference-error"', rendered)

    def test_textarea_and_select_share_accessible_supporting_text(self):
        textarea = render_to_string(
            "components/textarea.html",
            {
                "name": "notes",
                "help_text": "For internal use.",
                "readonly": True,
            },
        )
        select = render_to_string(
            "components/select.html",
            {
                "name": "category",
                "help_text": "Choose one category.",
                "options": [{"value": "otc", "label": "OTC"}],
            },
        )

        self.assertIn('aria-describedby="notes-help"', textarea)
        self.assertIn("readonly", textarea)
        self.assertIn('aria-describedby="category-help"', select)
        self.assertIn("appearance-none", select)

    def test_modal_description_is_programmatically_associated(self):
        rendered = render_to_string(
            "components/modal.html",
            {
                "modal_id": "confirmation",
                "title": "Confirm action",
                "description": "Review this change.",
                "body": "This cannot be undone.",
            },
        )

        self.assertIn('aria-describedby="confirmation-description"', rendered)
        self.assertIn('id="confirmation-description"', rendered)
        self.assertIn("data-modal-backdrop", rendered)


class DashboardNavigationTests(TestCase):
    role_items = {
        "Owner / Admin": {
            "Dashboard",
            "Sales",
            "Medicines",
            "Inventory",
            "Suppliers",
            "Customers",
            "Prescriptions",
            "Purchases",
            "Invoices",
            "Payments",
            "Returns & Refunds",
            "Reports",
            "Settings",
            "Logout",
        },
        "Pharmacist": {
            "Dashboard",
            "Sales",
            "Medicines",
            "Inventory",
            "Customers",
            "Prescriptions",
            "Invoices",
            "Returns & Refunds",
            "Logout",
        },
        "Inventory Manager": {
            "Dashboard",
            "Medicines",
            "Inventory",
            "Suppliers",
            "Purchases",
            "Logout",
        },
        "Accountant": {
            "Dashboard",
            "Invoices",
            "Payments",
            "Reports",
            "Logout",
        },
    }

    def navigation_for(self, role_name):
        group = Group.objects.create(name=role_name)
        user = get_user_model().objects.create_user(
            username=role_name.lower().replace(" ", "-").replace("/", ""),
            password="test-password",
        )
        user.groups.add(group)

        request = RequestFactory().get("/")
        request.user = user
        request.resolver_match = resolve("/")
        return dashboard_navigation(request)["dashboard_navigation"]

    def test_navigation_preserves_role_visibility(self):
        for role_name, expected_labels in self.role_items.items():
            with self.subTest(role=role_name):
                items = self.navigation_for(role_name)
                self.assertEqual({item["label"] for item in items}, expected_labels)

    def test_dashboard_is_active_and_future_modules_are_disabled(self):
        items = self.navigation_for("Owner / Admin")
        dashboard = next(item for item in items if item["label"] == "Dashboard")
        future_items = [
            item
            for item in items
            if item["label"] not in {"Dashboard", "Logout"}
        ]

        self.assertTrue(dashboard["is_active"])
        self.assertEqual(dashboard["url"], "/")
        self.assertTrue(all(item["url"] is None for item in future_items))

    def test_sections_and_post_logout_are_exposed_to_the_template(self):
        items = self.navigation_for("Owner / Admin")
        logout_item = next(item for item in items if item["label"] == "Logout")

        self.assertEqual(
            {item["section"] for item in items},
            {"Main", "Management", "Transactions", "Reports", "System"},
        )
        self.assertEqual(logout_item["url"], "/accounts/logout/")
        self.assertEqual(logout_item["method"], "post")
