# Generated by Django 6.1 on 2026-08-28 13:41

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_category',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_category_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('prescription_required', models.BooleanField(default=False)),
                ('low_stock_threshold_base', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('default_selling_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='catalog.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='catalog.manufacturer')),
            ],
            options={
                'db_table': 'catalog_medicine',
            },
        ),
        migrations.CreateModel(
            name='MedicineUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('conversion_to_base', models.DecimalField(decimal_places=6, max_digits=14)),
                ('is_base_unit', models.BooleanField(default=False)),
                ('purchase_allowed', models.BooleanField(default=True)),
                ('sale_allowed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='catalog.medicine')),
            ],
            options={
                'db_table': 'catalog_medicine_unit',
            },
        ),
        migrations.CreateModel(
            name='MedicineBarcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='catalog.medicineunit')),
            ],
            options={
                'db_table': 'catalog_medicine_barcode',
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='catalog_med_name_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='catalog_med_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold_base__isnull', True), ('low_stock_threshold_base__gte', 0), _connector='OR'), name='catalog_medicine_low_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('default_selling_price__gte', 0)), name='catalog_medicine_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='medicineunit',
            constraint=models.UniqueConstraint(fields=('medicine', 'name'), name='catalog_unit_medicine_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='medicineunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_base_unit', True)), fields=('medicine',), name='catalog_unit_one_active_base'),
        ),
        migrations.AddConstraint(
            model_name='medicineunit',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_to_base__gt', 0)), name='catalog_unit_conversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='medicineunit',
            constraint=models.CheckConstraint(condition=models.Q(('is_base_unit', False), ('conversion_to_base', Decimal('1.000000')), _connector='OR'), name='catalog_unit_base_conversion_one'),
        ),
    ]
